### ISSUE TITLE
Facebook Audience Network lock http requests

### ISSUE THREAD

**Issue by luigisaggese** [xamarin/FacebookComponents#1]
Dear, 
we have a big issue with FB Audience component.

We have integrating Facebook Audience Network on iOS with a placement but on different devices and FB accounts API answer is always this 

> [FBAudienceNetworkLog/FBAdProvider:137 <error>] Ad request error: Error Domain=com.facebook.ads.sdk Code=1001 "No fill" UserInfo={FBAdErrorDetailKey={ msg = "No fill. We are not able to serve ads to this person. Please refer to https://developers.facebook.com/docs/audience-network/faq#a12. If you are integrating Audience Network for the first time, you can use test ads https://developers.facebook.com/docs/audience-network/testing."; }, NSLocalizedDescription=No fill} 

We have referred also docs a12 but there are "No limits on iOS ads" and all accounts are logged to Facebook.

We have read carefully documentation and we have check condition of "No fill" on iOS and Android. 

We would like to use Facebook Native Ads in our job listing each 5 job advert we want show 1 Facebook Native Ads. 

What is strange is this case (on same device): 

Installing app in DEBUG MODE Facebook Native Ads are shown correctly 
Installing app in RELEASE MODE USING TESTFLIGHT Facebook Native Ads respond "No Fill" 
Same TestFlight app installed via APPSTORE Facebook Native Ads LOCK others HTTP requests. We have check it via Charles (http://www.charlesproxy.com/) and API call does not start because is in loading Facebook call. This happens on all devices that download app via APPSTORE. 

Our app is developed via Xamarin Component https://components.xamarin.com/view/fbaudiencenetworkios 

What seems really strange is same code on same device and same FB user (mine Luigi Saggese) on different release type have different behaviour. 
Debug Mode: OK 
Release Mode using TestFlight: "No Fill" without locking other API calls
App Store: No response locking other API calls 

On TestFlight mode we have found this answer on StackOverflow that seems realistic (http://stackoverflow.com/questions/29779758/facebook-native-ads-on-ios) "Test Flight rotates through a pool of IDFA's and hides the users true IDFA, making it difficult to identify a Facebook user – and that is required for delivering an ad." 

Please help us to solve this issue, we have also written to Facebook support and they say as that Xamarin is maintaining component.
https://developers.facebook.com/bugs/1050931391633784

**Comment by luigisaggese** [comment]
Any news?

**Comment by SotoiGhost** [comment]
Hi @luigisaggese 

A big apology for taking some time to give a reply.

We have just published the new version of FB Audience Network for iOS, can you try it? That version contains a fix that avoid linker from stripping the AdSizes class, that was causing some problems just on Release mode.

Let me know if that work for you.

Greetings,
Israel Soto.

**Comment by luigisaggese** [comment]
Hi @SotoiGhost,
I have binded FBAudiencdNetwork last version and I have solved my issues. If you want to compare my interface with your I will send you soon.

Let me know,
Luigi

**Comment by SotoiGhost** [comment]
Yes, if you have something that we haven't fixed yet, would be great!

You can fork the Xamarin Facebook repo and add your fix to our binding and then, make a PR so we can review your fix.

Also, if you want, you can send me your fix privately so I can review it.

Anyways, I'll close this issue, since it seems it is fixed.

Greetings,
Israel Soto.
