### ISSUE TITLE
Request for -> hot fix for 308 login error (challenge with + symbol) included in 4.38.1

### ISSUE THREAD

**Issue by AntRemo** [xamarin/FacebookComponents#103]
Our iOS users are complaining of the following error while signing in

> The operation couldn’t be completed. (com.facebook.sdk.login error 308.)

It appears to have been resolved in 4.38.1
https://github.com/facebook/facebook-objc-sdk/pull/922#issuecomment-436050897

I would greatly appreciate if you could upgrade the nuget packages.

Thanks 🙏

> VS bug [#751310](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/751310)

**Comment by SotoiGhost** [comment]
This will be updated in the following weeks.

**Comment by zavalishin** [comment]
Not sure about the rest but this error is easily reproducible in my iOS project. Very annoying as it aborts the login sequence and the user has to go through the entire sequence of Facebook screens again. Perhaps it deserves a higher priority? Thanks!

**Comment by AntRemo** [comment]
@zavalishin 
In the meantime, I reverted to 4.35.0 and as far as I know it is working properly now.

**Comment by SotoiGhost** [comment]
There's a PR with the update, will be merged soon.

**Comment by vixez** [comment]
Hello,
One of the apps I'm working has this issue as well.
Any ETA on when the new Facebook SDK NuGet package is released?

**Comment by ashleypringle** [comment]
Just chiming in to say our app is affected by this as well. Looking forward to a fix for this issue.
