### ISSUE TITLE
[Android] RegisterViewForInteraction missing from NativeAd and NativeBannerAd

### ISSUE THREAD

**Issue by AntRemo** [xamarin/FacebookComponents#104]
Step 4 of **Migration Steps** in the [SDK 4.99 Upgrade Guide](https://developers.facebook.com/docs/audience-network/upgrade_guide_android_4_99#changed) states:

> NativeAd interface changes: 
**registerViewForInteraction(View)** is replaced by **registerViewForInteraction(View, MediaView, AdIconView)** where AdIconView is optional. 
**registerViewForInteraction(View, List<View>)** is replaced by **registerViewForInteraction(View, MediaView, AdIconView, List<View>)** where AdIconView is optional. 

It appears that during the upgrade to 5.0.1 these methods were lost. The **NativeBannerAd** class also appears to be missing this method handler.

Please update the SDK to support Native Ads.
Thanks 🙂

> VS bug [#792686](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/792686)

**Comment by AntRemo** [comment]
Hi @Redth !

Any update on this issue?

Thanks 🙏

**Comment by AntRemo** [comment]
Just following up. Thanks :)

**Comment by SotoiGhost** [comment]
@AntRemo Those methods are being removed due to `MediaView` and `AdIconView` now inherit from  a private class. Will fix this.
