### ISSUE TITLE
[iOS] AccountKit Support One Time Code AutoFill on iOS 12 

### ISSUE THREAD

**Issue by nhdanh** [xamarin/FacebookComponents#105]
In iOS 12, when you receive an SMS message with an OTP or a verification code, the OS suggests the OTP in the keyboard’s quick type field. This can come in really handy because while it’s obviously possible to view the message and remember the OTP, it’s far easier to just tap on the quick type field and have it automatically entered in. 
But AccountKit not support this features. I can't set textContentType of textfield in AccountKit UI. I need set
otpTextField.textContentType = .oneTimeCode to get code from sms to keyboard.

Has AccountKit support it ? Add new feature to new version of AFK ? 

![9qovj](https://user-images.githubusercontent.com/32826936/50745845-e6ce0d00-125e-11e9-9eaa-09ee25d522bc.png)

**Comment by SotoiGhost** [comment]
@nhdanh Sorry for the delay to give a response.

You can set the property on C# side by using the following line of code:

```csharp
textField.TextContentType = UITextContentType.OneTimeCode;
```

Also, testing the sample, using the Facebook update to v4.39.1, I can confirm that AccountKit has support for OneTimeCode:

<img height="400" src="https://user-images.githubusercontent.com/5924210/52680761-458e4280-2eff-11e9-877a-0552019a5896.PNG" />

This update is in [review][1], I hope the update is released by this week.

[1]: https://github.com/xamarin/FacebookComponents/pull/107

**Comment by nhdanh** [comment]
can give me sample project or how to set textField.TextContentType = UITextContentType.OneTimeCode ?

**Comment by nhdanh** [comment]
@SotoiGhost can you help me ? How to set textField.TextContentType = UITextContentType.OneTimeCode in UI AccountKit ? Can give me sample ?

**Comment by SotoiGhost** [comment]
@nhdanh AFAIK, you cannot modify the properties of the views shown by the Account Kit. Also, Facebook has already set the `TextContentType` property to `OneTimeCode` in Account Kit. The test shared before is proof of that. The test was made using AccountKit v4.39.1.

Hope this helps you.

**Comment by nhdanh** [comment]
I was update AccountKit to 4.39.1. I will test it. Thank you

**Comment by nhdanh** [comment]
I was updated to newest version of xamarin accountkit. But still no Support One Time Code AutoFill on iOS 12
