### ISSUE TITLE
Need Xamarin.Facebook.Android v4.39

### ISSUE THREAD

**Issue by shpand** [xamarin/FacebookComponents#106]
Facebook fixed some bugs in the new release and it'd be great to have related xamarin sdk version. Thanks.

> VS bug [#792688](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/792688)

**Comment by SotoiGhost** [comment]
Facebook for Android will be updated by the following weeks.

**Comment by SotoiGhost** [comment]
@shpand Facebook for Android v4.40.0 has been pushed to NuGet. Just wait a bit for the indexing.

Best!
Israel Soto.
