### ISSUE TITLE
Facebook iOS Unable to get publish permission 

### ISSUE THREAD

**Issue by emmanuel128** [xamarin/FacebookComponents#108]
Hello, I created a new Xamarin project and I'm using `Xamarin.Facebook.iOS 4.38.0`.

At first my application is requesting read permissions to make the registration/login. 

``` c#
public static List<string> FacebookReadPermissions = new List<string> {
            "public_profile",
            "email"
};

.  .  .

loginManager.LogInWithReadPermissions(FacebookReadPermissions.ToArray(), this, (results, errors) => {
    .
    .
    .
}
```

Then I try to publish so I ask for `["publish_actions"]` permissions, but the token is always null and it shows the following message:

![image](https://user-images.githubusercontent.com/14911235/51632451-b7d5bd80-1f25-11e9-82ee-6f8fbc8fb3f0.png)

```c#
public static List<string> FacebookPublishPermissions = new List<string> {
            "publish_actions",
};

.  .  .

loginManager.LogInWithPublishPermissions(AppDelegate.FacebookPublishPermissions.ToArray(), this, (result, error) => 
{
    .
    .
    .
    if (result.Token == null)
    {
        // result is null
    }

    // Manage success
}
```

Any ideas?

**Comment by SotoiGhost** [comment]
@emmanuel128 According to a [New Facebook Platform Product Changes and Policy Updates][1], this is no longer possible to achieve. Facebook stated that:

> The publish_actions permission will be deprecated. This permission granted apps access to publish posts to Facebook as the logged in user. Apps created from today onwards will not have access to this permission. Apps created before today that have been previously approved to request publish_actions can continue to do so until August 1, 2018. No further apps will be approved to use publish_actions via app review. Developers currently utilizing publish_actions are encouraged to switch to Facebook's Share dialogs for web, iOS and Android.

Hope this helps you.

Best!
Israel Soto.

[1]: https://developers.facebook.com/blog/post/2018/04/24/new-facebook-platform-product-changes-policy-updates/?locale=en_US

**Comment by emmanuel128** [comment]
Thanks!
