### ISSUE TITLE
Facebook login causes you to be taken to its “Help Center” if we try to login multiple times 

### ISSUE THREAD

**Issue by Scy15** [xamarin/FacebookComponents#109]
My app has multiple login options; of which FB Login is one of the options. Clicking "cancel" on the "confirm login" page on facebook login causes you to be taken to a troubleshooting page the next time you attempt.

Steps: Open the app that is not currently logged in but has been logged in using facebook in the past.

1 - Click on Login (Existing User)

2 - Click Login with Facebook

3 - You should be taken to a "confirm login" page where is tells you "you previously logged in to App with Facebook"

4 - Click cancel and it takes you to the Login screen

5 - Press "Login with Facebook" again

6 - If done consecutively you will be taken to the Facebook Help Center

Please let me know if this is an expected behaviour or this needs to be handled.

The error I am getting when clicking cancel is:
error_reason=user_denied
&error=access_denied
&error_description=Permissions+error.

More info:
We are using Xamarin.Facebook.iOS.4.33.0 nuget package.

We are logging in to account as per "LoginButtonCompletedEventArgs.Result".
If "LoginButtonCompletedEventArgs.Result.Token" is not null, that is taken forward for successful login and hence proceeded.

In the reported bug scenario, we are getting
"LoginButtonCompletedEventArgs.Result.IsCancelled" as TRUE when we click "Cancel" in login confirmation page as well as "Done" in Help Center page.

Could you kindly try replicating the issue using the above mentioned package?
Also please let me know if this issue, "authorize/?error=access_denied&error_code=200&error_description=Permissions+error&error_reason=user_denied" when triggered multiple times could make Facebook suggest the user to report the app for any suspected attack?[](url)

NOTE:- I have tried all the changes mentioned in an issue closed recently. (https://github.com/xamarin/FacebookComponents/issues/88)

**Comment by SotoiGhost** [comment]
@Scy15 I have tested our sample using Facebook iOS package v4.35, v4.38 and v4.39.1 (which is in review process) and could not reproduce the issue. I share you a test that I made, I tried like 30 times before started recording.

<details>
<summary>Click here to see the test</summary>
<p>
<img height="400" src="https://user-images.githubusercontent.com/5924210/52811118-ebee5b00-3059-11e9-8d28-15a8b13a30e8.gif" />
</p>
</details>

Can you share a test case, please?

Thanks in advance!
Israel Soto.

**Comment by Redth** [comment]
We are closing this issue since no response was received.  Please open a new issue referring to this one if you have more information.
