### ISSUE TITLE
[Android] [4.38] App immediately closes after signed in.

### ISSUE THREAD

**Issue by ikazrima** [xamarin/FacebookComponents#110]
I can still get to the "Sign In" page, but app immediately closes after choosing continue or cancel.

Logging in doesn't trigger access token changed or profile changed.

Visual studio does not crash or trigger exceptions, and still has the debug process attached to my device after app closes down.

There were no errors logged.

Reverting to 4.26 fixes the issue.

Tested on Samsung SM P355 (API 25)
Tested on Android Emulator (API 27, 28)

**Comment by SotoiGhost** [comment]
@ikazrima I have tested FB component on a Samsung SM G930F (API 26) and emulators (API 25 and 27) and everything seems to be working for me. Can you provide a test case so I can investigate further? Thanks in advance!

**Comment by ikazrima** [comment]
> @ikazrima I have tested FB component on a Samsung SM G930F (API 26) and emulators (API 25 and 27) and everything seems to be working for me. Can you provide a test case so I can investigate further? Thanks in advance!

One thing I missed is that app is marked as "In development" in Facebook developer page.
My use case is as simple as follows:

If logged in:
1) Logout from all facebook logins on device (FB app & browser)
2) Login with Facebook button (in app)
3) Cancel or Continue when prompted

If not logged in:
1) (a) Login using FB app or device browser, and/or
    (b) Login with Facebook button (in app)
2) Cancel or Continue when prompted

The app closes immediately on both cases, with the debug process attached & running.
Cleaning and rebuilding the project have not effect.

Here's a modified code I'm using for your review.
[ikazrima facebook login.zip](https://github.com/xamarin/FacebookComponents/files/2870648/ikazrima.facebook.login.zip)

Without any modification of the original code, the login proceeds normally when reverted to 4.26

**Comment by SotoiGhost** [comment]
@ikazrima I noticed that you have `NoHistory` set to `true`. According to [Google's doc][1] about `NoHistory`:

> A value of "true" means that the activity will not leave a historical trace. It will not remain in the activity stack for the task, so the user will not be able to return to it. In this case, onActivityResult() is never called if you start another activity for a result from this activity.

So, when you hit the FB button, on some devices, FB will show another activity releasing your current activity, so when you hit cancel or you log in, releasing the FB activity, it will close the app since there's nothing in the stack.

Setting the `NoHistory` to false, make it work for me.

Hope this helps you.

Let me know you results.

[1]: https://developer.android.com/guide/topics/manifest/activity-element#nohist

**Comment by ikazrima** [comment]
@SotoiGhost removing the `NoHistory` works for me.

I need to find another way of disabling the user from going back to the login activity.
Thanks.
