### ISSUE TITLE
Facebook Ads - Can't make it work from the website

### ISSUE THREAD

**Issue by Emixam23** [xamarin/FacebookComponents#111]
Hey,

I'm working with the SDK since few days and they keep asking to update my SDK. I did so, from 4.30.0 to 4.38.8 (because they're asking at least 4.34.0). 

In debug mode (build from my mac), nothing worked once updated so I published the app on the store with the update. Now that the app is on the store, I still have the issue:

<img width="977" alt="screenshot 2019-02-09 at 14 57 02" src="https://user-images.githubusercontent.com/6987848/52521685-149ddb80-2c7b-11e9-95d2-5caf5d45b5df.png">

I am trying to use the **codeless event setup tool** but with no success: 

<img width="596" alt="screenshot 2019-02-09 at 15 00 54" src="https://user-images.githubusercontent.com/6987848/52521721-91c95080-2c7b-11e9-8ce6-991cfcd38999.png">

<img width="515" alt="screenshot 2019-02-09 at 14 59 46" src="https://user-images.githubusercontent.com/6987848/52521710-5fb7ee80-2c7b-11e9-85ba-c01bdece7f4b.png">

Any ideas?

Thanks !

**Comment by Emixam23** [comment]
Is the graph API linked to any of this logic? I mean, I tried to update my app to the v3.2 (beside using the sdk 4.38 but still nothing changes.. Is there anything I am missing?

**Comment by moustafashaban** [comment]
same issue here, any idea?

**Comment by Emixam23** [comment]
Still nothing...?

**Comment by SotoiGhost** [comment]
@Emixam23 Facebook iOS v4.39.1 has been released, can you try with that version and see what happens?

**Comment by Emixam23** [comment]
Ok I will try a bit later in the day :) Does it needs to be an app from the store and install from it? Can it be an app installed via a debugging tool?

**Comment by SotoiGhost** [comment]
@Emixam23 I don't have the right answer for that. We have faced this kind of warnings before, but FB is not clear with where the warning comes from or with the reason of the upgrade. Most of the time, it's related to the Graph API version, but v4.38.1 uses the most recent version.

So, my suggestion is to update where you think is necessary to be updated.

Hope this helps you.

**Comment by moustafashaban** [comment]
it is now working fine on IOS (4.39.1) but not on Android (4.38.0)

![image](https://user-images.githubusercontent.com/42233556/53475234-85693400-3a80-11e9-9c98-fec220ff99e3.png)

**Comment by SotoiGhost** [comment]
Hi guys! Just letting you know that we have just pushed to NuGet the v4.40.0 of both platforms. Hope this fixes the problem.

Best!
Israel Soto.
