### ISSUE TITLE
Media Plugin issues in Android

### ISSUE THREAD

**Issue by Scy15** [xamarin/FacebookComponents#116]
* [ ]  Xam.Plugin.Media version : 4.0.1.1

While opening the video in Xamarin forms, the download button on the Video player just enables the user to tap on it, without performing the download functionality. Is it possible to remove that option from the tab? Or can the video be downloaded?

**Comment by SotoiGhost** [comment]
Moved this issue to the plugin's owner repo: jamesmontemagno/MediaPlugin#675
