### ISSUE TITLE
Please update Audience Network SDK to latest version

### ISSUE THREAD

**Issue by AntRemo** [xamarin/FacebookComponents#119]

**Comment by AntRemo** [comment]
Hi @Redth 

Any updates on this. I just received an email from Facebook stating

> We've detected that one or more of your apps are using older versions of the Audience Network SDK.

Many thanks 🙏

**Comment by Redth** [comment]
@SotoiGhost can you please work on updating these?

**Comment by Redth** [comment]
For Android we can update to 5.3.0 and iOS it looks like 5.3.1.

**Comment by AntRemo** [comment]
Not to nag, but Facebook just sent me another email. Hopefully it can be updated soon 😊

**Comment by AntRemo** [comment]
Hi @Redth @SotoiGhost

Is there anything I can do to assist with updating? Thanks.

**Comment by SotoiGhost** [comment]
@AntRemo Facebook Audience Network for [iOS v5.3.2][1] and [v5.4.0 for Android][2] are live now on NuGet.

[1]: https://www.nuget.org/packages/Xamarin.Facebook.AudienceNetwork.iOS/
[2]: https://www.nuget.org/packages/Xamarin.Facebook.AudienceNetwork.Android/
