### ISSUE TITLE
Facebook SDK Error

### ISSUE THREAD

**Issue by ufukhawk** [xamarin/FacebookComponents#121]
I use Xamarin.Forms, but I do the necessary actions on the iOS side, but Facebook does not verify the update.
![facebook](https://user-images.githubusercontent.com/30172226/58231986-057dfd80-7d41-11e9-9180-abce13b8a3f7.png)
Error Message : 

![Untitled](https://user-images.githubusercontent.com/30172226/58232029-23e3f900-7d41-11e9-9bdd-c28149cc7e32.png)

**Comment by ufukhawk** [comment]
I using Plugin Xamarin.Facebook.iOS (4.39.1)

**Comment by SotoiGhost** [comment]
@ufukhawk Are you still facing this issue?

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue, please, open a new issue related to this. Thanks!
