### ISSUE TITLE
Facebook SDK v5.0

### ISSUE THREAD

**Issue by traceyhemp12** [xamarin/FacebookComponents#122]
Hi,

Is there an update for the Facebook SDK on the horizon? Facebook is advising to upgrade to v5.0.  Currently the SDK is only updated to version 4.40.0  https://www.nuget.org/packages/Xamarin.Facebook.Android/
Thanks for any insight.

**Comment by AntRemo** [comment]
Hi @traceyhemp12 

FYI: Same request here: https://github.com/xamarin/FacebookComponents/issues/119

**Comment by ajpinedam** [comment]
@Redth  I would like to take on this task if it's still available.

**Comment by Redth** [comment]
@SotoiGhost may have already started on this, let's wait for him to chime in :)

**Comment by SotoiGhost** [comment]
Facebook 5.x.x has been published to NuGet. Some of them need to be indexed yet.
