### ISSUE TITLE
Unable to find a version of 'Xamarin.Facebook.Login.Android' that is compatible with 'Xamarin.Facebook.Android 5.0.3 constraint: Xamarin.Facebook.Login.Android (>= 5.0.3)

### ISSUE THREAD

**Issue by softsan** [xamarin/FacebookComponents#131]
Getting this error while updating Xamarin.Facebook.Android 5.0.3 

`Unable to find a version of 'Xamarin.Facebook.Login.Android' that is compatible with 'Xamarin.Facebook.Android 5.0.3 constraint: Xamarin.Facebook.Login.Android (>= 5.0.3)'.
`

Thanks.

**Comment by SotoiGhost** [comment]
@softsan We had a problem internally when we were publishing the NuGets. We are fixing this ASAP. Sorry for the inconveniences.

**Comment by softsan** [comment]
How long does it takes to update the NuGet? Also i don't see yet an update for facebook iOS sdk. 
Thanks.

**Comment by SotoiGhost** [comment]
@softsan Sorry for the waiting time. The NuGet has been pushed to NuGet. Some of them need to be indexed yet. The updates include Android and iOS bits. Hope this helps you. Best! And sorry again for the inconveniences.
