### ISSUE TITLE
{400: An internal consistency error has occurred: 406: No access token: cannot retrieve account}

### ISSUE THREAD

**Issue by NVentimiglia** [xamarin/FacebookComponents#136]
I am experimenting with Account Kit for android. I have the package installed, and when I try to use the SDK, I get an error.

> {400: An internal consistency error has occurred: 406: No access token: cannot retrieve account}

```
 private void FbOnClick(object sender, EventArgs eventArgs)
        {
            myView = (View)sender;
            AccountKit.GetCurrentAccount(this);
        }


        public void OnError(AccountKitError error)
        {
            Snackbar.Make(myView, "OnError " + error.UserFacingMessage, Snackbar.LengthLong)
                .SetAction("Action", (Android.Views.View.IOnClickListener)null).Show();
        }

        public void OnSuccess(Java.Lang.Object result)
        {
            Snackbar.Make(myView, "OnSuccess ", Snackbar.LengthLong)
                .SetAction("Action", (Android.Views.View.IOnClickListener)null).Show();
        }
```

I noticed this related issue  :
> https://stackoverflow.com/questions/39397393/getting-accesstoken-null-in-facebook-accountkit-android-device 

Which instructs a custom configuration. I attempted to do this, but I cant find my way how to configure the SDK through the Xamarin abstraction layer. I tried to launch the intent manually, but that did not work out either.

**Comment by SotoiGhost** [comment]
@NVentimiglia Are you still facing this issue?

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue, please, open a new issue related to this. Thanks!
