### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by alwydl** [xamarin/FacebookComponents#137]
Could at least update/add some documetation for how to use.
The samples are using obsolete methods, and are all in one. There is no info anywhere on how to start using the sdk.
Or at least which methods are from which part of the sdk.

I know this will be closed, but I needed to vent.

**Comment by garie** [comment]
No kidding. Release notes would be great, too. There were breaking changes between 4.40.0 and 5.0.2 that I have no idea how to fix.

**Comment by gaurangnirmal** [comment]
Yes. **Can you please share the link of how to use these components in Xamarin.Forms Projects?**
I researched for the official documents but couldn't find any, though i referred [the official document for AccountKit from Facebook](https://developers.facebook.com/docs/accountkit/android). and converted my code into c# syntax in my Xamarin.Android project.
So, If there is no documents available for this, lets know and then, Kindly please create a one and share here.

**Comment by Redth** [comment]
Hi folks, I can appreciate it's frustrating to deal with breaking changes between versions.  Unfortunately these are generally out of our control as the breaking changes are happening in Facebook's native SDK, and we just provide the bindings to use those API's.

As for guides on using the API's, the best idea is to look at Facebook's official documentation.  You'll have to do a bit of a porting mental exercise, but the C# usage generally looks similar to the obj-c and especially java documentation.  Unfortunately there is no cross platform C# API for any of these, you'll have to write your own dependency service or use a similar pattern to do things from shared code.
