### ISSUE TITLE
[iOS] CoreKit v5.0.2 crashes on ARMv7 (32bits) devices

### ISSUE THREAD

**Issue by fdnhkj** [xamarin/FacebookComponents#138]
Since release 5.0.2, the Xamarin.iOS app I am working on is crashing on ARM32 devices. 

After inspecting the CoreKit 5.0.2 nuget package, I noticed the `info.plist` within the `FBSDKCoreKit.framework` has `ARM64` as `Required device capabilities` (cf. screenshot).

I had a look at the CoreKit framework from FacebookSDK and their info.plist does not specify ARM64.

Could this be an issue due to the building of the nugets packages within `Xamarin/FacebookComponents`?
For example, the following build setting (in cocoapods?) being set to `YES`: `Build Active Architecture Only`.

<img width="802" alt="Screenshot 2019-08-08 at 11 04 55" src="https://user-images.githubusercontent.com/5569608/62690320-cfa9f600-b9cc-11e9-970c-a3cb1e3d3dd5.png">

**Comment by AntRemo** [comment]
I recently had several users, using iPhone 5, contact me that they are no longer able to use the app. 

One user was able to send me the Diagnostics log and it included the following: 

`DYLD, Library not loaded: @rpath/FBSDKLoginKit.framework/FBSDKLoginKit | Referenced from: /var/containers/Bundle/Application/{GUID}/{AppBundleName}.app/{AppBundleName} | Reason: image not found`

I believe it is the same issue.

Hopefully, there is a quick solution for the problem.

**Comment by AntRemo** [comment]
@Redth @SotoiGhost 

Is this something that can be quickly and easily be resolved?

Thanks 🙏

**Comment by seansparkman** [comment]
I have also run into this issue as well.
@fdnhkj, Are you seeing the crash with 4.40.0?

**Comment by fdnhkj** [comment]
@AntRemo same crash report on my side.
@seansparkman No, only with 5.0.2. I had to rollback to v4.40.0 for my application until this issue is fixed.

**Comment by Remi-B** [comment]
I also have the same issue with my App. I would also add that when the app is packaged for Ad-Hoc distribution, the app is launching normally on 32bits devices.
Does any one have an explication about why is this working in this case ? 
Maybe it can be a hint about how to fix this issue…

**Comment by fdnhkj** [comment]
@Remi-B It is because the App Store and TestFlight use a process called _App Slicing_.
See this video for more info: https://developer.apple.com/videos/play/wwdc2015/404/

For info, I already investigated and found what the issue is (see issue report above).
The 5.0.2 nuget package was built while `ARM64` only was specified as supported architecture (not ARMv7).

So probable there was a mistake in the build step before publishing the nugget that resulted in having only `ARM64` in the `info.plist` `Required device capabilities`.

**Comment by alexlobanov** [comment]
@fdnhkj - yes you totally right, above issue exist only on TestFlight / AppStore because of App Slicing.

The reason because you see `ARM64` value exist in `Required device capabilities` property is because of changed build process on `FacebookComponents` recently. Currently for `LIPO` command they use `ARM64` specific build that has those property in `INFO.plist.`

I created PR that will fix those issue. This was verified on AppStore and TestFlight already for ARMv7 and ARM64 build.
