### ISSUE TITLE
Login does not work on iOS 13

### ISSUE THREAD

**Issue by Cheesebaron** [xamarin/FacebookComponents#154]
When trying to call `LogIn` on `LoginManager` on iOS 13, it consequently shows the following error in the log: 

```
-canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
```

The `LoginManagerLoginResult` returns cancelled.

This issue looks like it has been resolved in 5.8.0: https://github.com/facebook/facebook-ios-sdk/commit/6b061099f339ef0e8bde2e2c2163ef5a3c1b8340#diff-72593591275d63edfb1bfad837e4c32f

Please bump the version this binding is created against.

**Comment by SotoiGhost** [comment]
@Cheesebaron The issue mentioned was fixed in Facebook iOS v5.4.0. The current version of Xamarin Facebook for iOS is v5.6.0 which should have the fix of this. The fix seems to be working as others mentioned on resolved issue #143. 

Facebook will be updated soon, but right now is not a high priority.

**Comment by Cheesebaron** [comment]
Well... It does _not_ work in the current version. After I bumped it to 5.8.0 Facebook login started to work.

This is _not_ fixed!

**Comment by SotoiGhost** [comment]
@Cheesebaron can you provide a test case with the issue? I tested our samples and the login seems to be working as expected. This was tested on the simulator and on a device with iOS 13.

**Comment by Cheesebaron** [comment]
I am Sorry! I think something was cached on my machine. It looks like it is working with 5.6.0.
