### ISSUE TITLE
Native login doesn't work with Facebook iOS SDK

### ISSUE THREAD

**Issue by iforlife** [xamarin/FacebookComponents#16]
Hi,
I tried both samples that are included with the component and both only open the web view :(

Could someone please update the sample so they actually do open the native UI when logging in?
Or maybe there is a bug?!?

Just in case - all works when logging through the web view for both samples. Just the native UI will not show :(

Also - I'm running them from VS and all is setup on the Mac so I can deploy on iPhone device where Facebook app is installed.

Regards.

**Comment by pocheshire** [comment]
@iforlife 
try set login behavior like 
`login.LoginBehavior = Facebook.LoginKit.LoginBehavior.SystemAccount;`

**Comment by duckwaffle** [comment]
Any updates on this? Possibly @bholmes ? You've been pretty active on this repo.

**Comment by Redth** [comment]
This appears to be by design of the Facebook SDK:

https://developers.facebook.com/blog/post/2015/10/29/Facebook-Login-iOS9/

**Comment by SotoiGhost** [comment]
Facebook added a "Login with Facebook app" button in their Login flow. I'm closing this issue now.
