### ISSUE TITLE
Doesn't work with App Bundle

### ISSUE THREAD

**Issue by shubhamkumarnayak** [xamarin/FacebookComponents#161]
After updating the plugin I am unable to use app bundle to upload in play store, this is the error I am getting.

**Upload failed**

> Your app bundle targets the following unrecognised languages: fb. The list of supported language codes can be found in the [IANA registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry). Invalid languages caused by third-party libraries can be excluded using the [resConfigs](https://developer.android.com/studio/build/shrink-code#unused-alt-resources) Gradle property.

**Comment by garie** [comment]
This is fixed in the Android SDK v5.11.2. Should be a quick fix, hopefully someone can get this in ASAP as it's blocking my builds. 
https://github.com/facebook/facebook-android-sdk/issues/614

**Comment by garie** [comment]
I tried adding property `<AndroidResgenExtraArgs>-c en</AndroidResgenExtraArgs>` and this did _not_ fix the issue, so afaik there is no workaround.

**Comment by garie** [comment]
For others to be able to find this more easily, I got the error "AAB upload failed. The bundle targets unrecognized languages: fb." Not sure why the language for mine is different from yours. I am releasing in App Center which uses the API, which may have different wording from the UI in the Play Store Console.

**Comment by shubhamkumarnayak** [comment]
@garie if you see my comment, mine is also the same error and language is also "fb"

**Comment by Redth** [comment]
We will get an update out for this ASAP

**Comment by garie** [comment]
Thanks, confirmed my build in App Center works after updating to the latest package.
