### ISSUE TITLE
Xamarin.Android and Xamarin.iOS bindings for Facebook SDK 7

### ISSUE THREAD

**Issue by vladislav-sidorovich** [xamarin/FacebookComponents#172]
Could you please provide new Xamarin.Android and Xamarin.iOS bindings for Facebook SDK 7.0.1?

**Comment by AndreyFromGomel** [comment]
@SotoiGhost, @Redth, @mattleibow Hi, I'm sorry for mention you all but I don't know who maintain this repository and may review this issue and possible resolve it.
Facebook sent alert to App Dashboard which says that our application will not work correctly in several scenarios unless we update Facebook SDK to 6.3+:
![image](https://user-images.githubusercontent.com/46677631/87560851-8f66f380-c6c4-11ea-8f2c-711ac264d884.png)
We rely on Xamarin bindings for FB Mobile SDK so don't have many other options to mitigate this issue.
Could you please check and clarify may we expect new iOS and Android bindings before the middle of September?

**Comment by softsan** [comment]
We also need updates of latest of FB Sdk. The last nuget package were updated 8months ago. So any ETA when can you guys update this? Thanks.

**Comment by mattleibow** [comment]
The changes were merged yesterday. I'll be pushing them out soon.

**Comment by mattleibow** [comment]
All the new packages are out!

**Comment by AndreyFromGomel** [comment]
Thank you!
