### ISSUE TITLE
AndroidX Support

### ISSUE THREAD

**Issue by joe-ifit** [xamarin/FacebookComponents#173]
Xamarin.Facebook.Android has a dependency on Android support Libraries.  Is there any timeline on an AndroidX version?

- Xamarin.Facebook.Android
  -  Xamarin.Facebook.Share.Android
     - Xamarin.Android.Support.v7.AppCompat

**Comment by bholmes** [comment]
The updated version of Facebook for Android point to AndroidX.

https://github.com/xamarin/FacebookComponents/blob/master/Facebook.Android/source/facebook-share/facebook-share.csproj#L62

**Comment by EmilAlipiev** [comment]
what does this exactly mean? Because when i try to update to the latest version, I get a warning that I must install Xamarin.Android.Support.v7.AppCompat. Was that AndroidX update not pushed yet as nuget ?
