### ISSUE TITLE
Immediate App Crash On Startup

### ISSUE THREAD

**Issue by osmanghaziurdu** [xamarin/FacebookComponents#174]
I'm testing a Facebook Audience Network Ads in My real physical device Huawei Tit AL00 Android Version 5.1. I am On A Visual Studio. When I simply deploy app to device, this error occurs and app crashes immediately. But when i DEBUG directly from Visual Studio, the app takes some time but Runs successfully and also ads displayed. I can provide you a solution on which i working ...... What problem this should be ? If i have to initialize some code in Main Activity or some thing else?

**Comment by osmanghaziurdu** [comment]
I have Solve This Issue.

**Comment by jonathanantoine** [comment]
Hello @osmanghaziurdu  how did you do it :) ?
