### ISSUE TITLE
Please Update The Facebook Audience Network V to 5.10

### ISSUE THREAD

**Issue by osmanghaziurdu** [xamarin/FacebookComponents#175]
I'm setting up my App In FAN Network. They are Asking me to update my SDK Version to 5.10 Unless i can't setup my App. Current Nuget Version Of SDK is 5.6. Please update it as soon as possible. Thanks

**Comment by mattleibow** [comment]
This will be going out soon. Waiting for CI to finish and then it's publishing time!

**Comment by mattleibow** [comment]
All the new packages are out!!!
