### ISSUE TITLE
Where are the methods to enable auto event logging? 

### ISSUE THREAD

**Issue by titonton** [xamarin/FacebookComponents#184]
Step # 7 has a some methods that allow us to enable some settings for automatic logging. I don't think there any methods on this package that do the same thing. It is present in Android as FacebookSdk.AutoLogAppEventsEnabled. I was not able to find an equivalent for iOS.

https://developers.facebook.com/docs/app-events/getting-started-app-events-ios/

**Comment by titonton** [comment]
Apologies. I found out where it is. It is under the Settings class. Closing this.

**Comment by shubhamkumarnayak** [comment]
> Apologies. I found out where it is. It is under the Settings class. Closing this.

It will be great if you can mention the setting that you find as well, it will help everyone who don’t know it.

**Comment by titonton** [comment]
> > Apologies. I found out where it is. It is under the Settings class. Closing this.
> 
> It will be great if you can mention the setting that you find as well, it will help everyone who don’t know it.

Of course. It is a property in the Settings class of the Facebook.CoreKit namespace called AutoLogAppEventsEnabled.
```
import Facebook.CoreKit;
Settings.AutoLogAppEventsEnabled = true
```
