### ISSUE TITLE
Add Bindings for Account Kit

### ISSUE THREAD

**Issue by bholmes** [xamarin/FacebookComponents#19]
Add iOS and Android binding libraries for Facebook's [Account Kit](https://developers.facebook.com/docs/accountkit)

**Comment by aamir-amwar** [comment]
Hi, when we have a Facebook Account Kit library for Xamarin.iOS and Xamarin.Android?

**Comment by rudacs** [comment]
Nothing yet?

**Comment by S1r-Lanzelot** [comment]
OK - so obviously this is still needed and some people want it, including myself. Is there any work done towards this enhancement, if so how is it coming? If not, was it determined this would not be worth binding - if so, why?

If it just a matter of man hours - how can myself/community help to get this going? Does someone just need to start a branch on creating the bindings via https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/ and https://docs.microsoft.com/en-us/xamarin/ios/platform/binding-objective-c/

Thanks

**Comment by Redth** [comment]
@S1r-Lanzelot this is not a high priority item for us at this time.  We would definitely welcome pull requests to add bindings for these libraries.  We just ask that you follow the existing file structure and build script patterns we have in place in the repository :)

**Comment by S1r-Lanzelot** [comment]
@Redth , thanks for your reply, I'm working on this now so I'll be sure to submit a PR with the proper structure/scripts when I am happy with it. Android / iOS may be staggered depending on my time.

**Comment by S1r-Lanzelot** [comment]
@Redth and @bholmes - please review the PRs for closing out this issue (adding Account Kit).... Feedback would be greatly appreciated.

https://github.com/xamarin/FacebookComponents/pull/61
https://github.com/xamarin/FacebookComponents/pull/63

Thanks.

**Comment by Redth** [comment]
Thanks, it's definitely on my short list!  Will be looking at them very soon.

**Comment by S1r-Lanzelot** [comment]
This issue can now be closed.
