### ISSUE TITLE
API 9.0 support?

### ISSUE THREAD

**Issue by joshuatantonflynn** [xamarin/FacebookComponents#193]
We just got an email from facebook telling us we need to update our SDKs to v9.0.0. However, the newest nuget package is 7.1.0 for Android and 7.1.1 for iOS.

Any plans to release 9.0 for xamarin soon?

**Comment by thisisthekap** [comment]
I am starting to do the update fpr both android and ios.

For Android, #194 Is blocking the update. I already created a PR for that one.

Going to continue on the updates next week.

**Comment by quakke** [comment]
This has become very important to me. Are there any updates here ?

**Comment by thisisthekap** [comment]
@quakke Related to #192

**Comment by thisisthekap** [comment]
Update done and working on my side. Needs some more polishing. Going to create a PR soon.

**Comment by thirdactse** [comment]
@thisisthekap The marketing people are currently throwing darts at my picture and asking why they can't advertise on fb anymore to iOS users ;D Any update on the sdk? Big thanks for doing this!

**Comment by thisisthekap** [comment]
@thirdactse Thanks to @dalexsoto, the review process finally started. Fingers crossed that it won't take that long.

If you need to have the updated nugets asap, feel free to check out my branch to build the nugets yourself. (Without any warranty of course 😉)
