### ISSUE TITLE
XamarinFacebookAndroid forces building with multi-dex

### ISSUE THREAD

**Issue by muhaym** [xamarin/FacebookComponents#27]
After upgrading to latest XamarinFacebookAndroid using nuget, I am receiving the following error while building.

My guess is the inclusion of support library custom tab as dependency.

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: error : Tool exited with code: 2. Output: 
trouble writing output: Too many field references: 66329; max is 65536.
You may try using --multi-dex option.
References by package:
     3 android.accounts
    26 android.app
     1 android.content
    30 android.content.pm
     6 android.content.res
     3 android.database
    44 android.graphics
     2 android.media
     1 android.media.browse
     2 android.net
    18 android.os
     3 android.print
     1 android.provider
     8 android.runtime
  2582 android.support.customtabs
  2516 android.support.design
    52 android.support.design.internal
   610 android.support.design.widget
  2669 android.support.graphics.drawable
  2516 android.support.graphics.drawable.animated
  2516 android.support.v13
    32 android.support.v13.app
  2516 android.support.v4
    13 android.support.v4.accessibilityservice
    17 android.support.v4.animation
   770 android.support.v4.app
   110 android.support.v4.content
     1 android.support.v4.content.pm
     9 android.support.v4.graphics
    42 android.support.v4.graphics.drawable
     4 android.support.v4.hardware.display
    12 android.support.v4.hardware.fingerprint
     9 android.support.v4.internal.view
   337 android.support.v4.media
   272 android.support.v4.media.session
     5 android.support.v4.net
    19 android.support.v4.os
    49 android.support.v4.print
     9 android.support.v4.provider
     5 android.support.v4.speech.tts
    55 android.support.v4.text
    74 android.support.v4.util
   385 android.support.v4.view
   112 android.support.v4.view.accessibility
     8 android.support.v4.view.animation
   495 android.support.v4.widget
   572 android.support.v7.app
  2516 android.support.v7.appcompat
  2516 android.support.v7.cardview
    18 android.support.v7.graphics.drawable
   422 android.support.v7.media
  2516 android.support.v7.mediarouter
  2516 android.support.v7.recyclerview
     1 android.support.v7.text
     2 android.support.v7.transition
    93 android.support.v7.util
    77 android.support.v7.view
   191 android.support.v7.view.menu
  1352 android.support.v7.widget
    89 android.support.v7.widget.helper
     1 android.support.v7.widget.util
     5 android.text
    13 android.util
    18 android.view
     1 android.view.inputmethod
    16 android.widget
   158 bolts
  2516 bolts.applinks
  2917 com.facebook
   159 com.facebook.appevents
    39 com.facebook.appevents.internal
    46 com.facebook.applinks
   550 com.facebook.internal
   174 com.facebook.login
    81 com.facebook.login.widget
    32 com.facebook.messenger
    51 com.facebook.share
   360 com.facebook.share.internal
   113 com.facebook.share.model
   124 com.facebook.share.widget
  2510 com.google.android.gms
    20 com.google.android.gms.actions
    13 com.google.android.gms.ads.identifier
  2562 com.google.android.gms.auth
     6 com.google.android.gms.auth.account
  2528 com.google.android.gms.auth.api
    77 com.google.android.gms.auth.api.credentials
    23 com.google.android.gms.auth.api.credentials.internal
    44 com.google.android.gms.auth.api.proxy
    46 com.google.android.gms.auth.api.signin
    31 com.google.android.gms.auth.api.signin.internal
  2510 com.google.android.gms.base
    99 com.google.android.gms.common
    93 com.google.android.gms.common.api
    41 com.google.android.gms.common.data
    46 com.google.android.gms.common.images
   188 com.google.android.gms.common.internal
     1 com.google.android.gms.common.internal.safeparcel
     4 com.google.android.gms.common.server
    12 com.google.android.gms.common.server.converter
    33 com.google.android.gms.common.server.response
    63 com.google.android.gms.common.stats
    22 com.google.android.gms.common.util
    27 com.google.android.gms.dynamic
     2 com.google.android.gms.dynamite.descriptors.com.google.android.gms.flags
    16 com.google.android.gms.flags.impl
  2510 com.google.android.gms.identity
    18 com.google.android.gms.identity.intents
    20 com.google.android.gms.identity.intents.model
     6 com.google.android.gms.iid
  1594 com.google.android.gms.internal
     5 com.google.android.gms.location.places
    18 com.google.android.gms.phenotype
    11 com.google.android.gms.playlog.internal
     6 com.google.android.gms.security
    26 com.google.android.gms.signin.internal
  2558 com.google.android.gms.tasks
  2601 com.koushikdutta.urlimageviewhelper
   371 com.squareup.okhttp
    92 com.squareup.okhttp.internal
   246 com.squareup.okhttp.internal.framed
   134 com.squareup.okhttp.internal.http
    15 com.squareup.okhttp.internal.io
    16 com.squareup.okhttp.internal.tls
  2510 com.zemose.android
  2543 de.hdodenhof.circleimageview
    34 dk.ostebaronen.droid.viewpagerindicator
    11 java.lang
     7 java.lang.annotation
     6 java.net
     1 java.nio
     6 java.util
     2 java.util.concurrent
     3 java.util.logging
     2 md5048a04284979bff265231e98628579ce
     4 md526b7ac14cffc1a788e82c7b73f3add08
     4 md531f8cc8d4d39b2fa02686ee0eb368905
    48 md5889544b40dfd8cffcf9a8ed30ef46386
     4 md595f4b8ab717b9da13f11267a86077f20
     4 md59f70a99687498e7ba187118950981d26
     2 md5ea7fe437769f29ec64df3b4cdd3cbce2
     6 mono
     4 mono.android.accessibilityservice
     2 mono.android.accounts
    12 mono.android.animation
    31 mono.android.app
     2 mono.android.bluetooth
    20 mono.android.content
     2 mono.android.database.sqlite
     6 mono.android.drm
     6 mono.android.gesture
     2 mono.android.graphics
     2 mono.android.graphics.drawable
     8 mono.android.hardware
     2 mono.android.hardware.display
     2 mono.android.hardware.input
     2 mono.android.inputmethodservice
     8 mono.android.location
    60 mono.android.media
    16 mono.android.media.audiofx
     2 mono.android.media.effect
     2 mono.android.media.midi
     2 mono.android.media.session
     2 mono.android.media.tv
     2 mono.android.net
     6 mono.android.net.nsd
     2 mono.android.net.sip
    18 mono.android.net.wifi.p2p
     2 mono.android.nfc
    10 mono.android.os
    10 mono.android.preference
     2 mono.android.renderscript
     6 mono.android.runtime
     6 mono.android.sax
     2 mono.android.speech
     4 mono.android.speech.tts
     8 mono.android.support.design.widget
     2 mono.android.support.v4.app
     4 mono.android.support.v4.content
     2 mono.android.support.v4.media.session
     2 mono.android.support.v4.os
    14 mono.android.support.v4.view
     8 mono.android.support.v4.widget
     6 mono.android.support.v7.app
    30 mono.android.support.v7.widget
     2 mono.android.text
     2 mono.android.transition
    72 mono.android.view
     4 mono.android.view.accessibility
     2 mono.android.view.animation
     2 mono.android.view.textservice
     8 mono.android.webkit
    72 mono.android.widget
     6 mono.com.facebook.internal
     2 mono.com.facebook.login.widget
     2 mono.com.facebook.share.widget
     2 mono.com.google.android.gms.common.api
     2 mono.com.google.android.gms.common.images
     2 mono.com.google.android.gms.security
     6 mono.com.google.android.gms.tasks
     4 mono.java.lang
     2 mono.java.util
     2 mono.javax.xml.transform
   100 okio
     2 opentk
     2 opentk.platform.android
     2 opentk_1_0
     2 opentk_1_0.platform.android
     1 org.json

```
 22 Warning(s)
 1 Error(s)
```

Time Elapsed 00:00:30.9558260

---------------------- Done ----------------------

Build: 1 error, 22 warnings

**Comment by AlexanderOsokin** [comment]
Same issue

**Comment by newky2k** [comment]
@muhaym can you try the latest version to see if this is still the issue is an problem

**Comment by newky2k** [comment]
no response for two weeks closing
