### ISSUE TITLE
Facebook iOS

### ISSUE THREAD

**Issue by rmenezes** [xamarin/FacebookComponents#31]
Why Xamarin Facebook iOS binding don't binding [[FBSDKSettings accessTokenCache] fetchAccessToken]?

**Comment by SotoiGhost** [comment]
@rmenezes I cannot find a definition for `accessTokenCache` inside of FBSDKCoreKit library. Am I missing something?

**Comment by rmenezes** [comment]
@SotoiGhost this definition is inside the FBSDKSettings.m so since function is not inside the header file that's why is not in the Xamarin Facebook Library. I figure out this one week later.

**Comment by SotoiGhost** [comment]
Yeah, the same thing happened to me. Don't worry, I'm closing this issue now.

Best.
