### ISSUE TITLE
Update Facebook libraries?

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/FacebookComponents#33]
Facebook (for iOS at least) is now on 4.20.2: https://github.com/facebook/facebook-ios-sdk/releases

Is there any plans to update these components?

I took a stab at doing it myself by modifying `GIT_REPO_TAG` in the Makefile, but I get a build error:
```
cp: ../Bolts-IOS/build/ios/Bolts.framework: No such file or directory
```
I think this is coming from `build_distribution_xamarin.sh`.

This is an issue for us, because there is a [bug in the iOS Facebook SDK 4.18](http://stackoverflow.com/questions/41064234/facebook-sdk-crashes-in-application-delegate) that breaks login. Right now we are having to run the 4.16.1 version of the Xamarin.Facebook.iOS NuGet package because of this.

**Comment by SotoiGhost** [comment]
@jonathanpeppers the script is not working because Facebook remove the `git submodule` command that clone all dependencies repos.

Seems that since FB iOS v 4.19.0, iOS 7 was dropped, due to this, we are going to change the way we get the Facebook binaries. We are working on this.

**Comment by jonathanpeppers** [comment]
Ok, thanks.

Do you know how long it might be before a new release? Sometime in April?

**Comment by SotoiGhost** [comment]
The update was released, I'm closing this issue now.
