### ISSUE TITLE
CurrentAccessToken null after a successful login followed by an app restart (4.18.0.1)

### ISSUE THREAD

**Issue by manuelcosta74** [xamarin/FacebookComponents#35]
Hi guys

after updating this component to last available 4.18.0.1 in Xamarin components portal we started to have an issue with AccessToken.CurrentAccessToken. It returns null after a successful login followed by an app restart.
Of course that we do have all things that fb tell us to do 

public override bool FinishedLaunching
...

Profile.EnableUpdatesOnAccessTokenChange(true);
Settings.AppID = FacebookAppId;
Settings.DisplayName = DisplayName;

return ApplicationDelegate.SharedInstance.FinishedLaunching(app, options);

This seems to be related to permissions or so. Any guess?

cheers
Manuel

**Comment by SotoiGhost** [comment]
Are you still facing this issue?

**Comment by newky2k** [comment]
no response since november
