### ISSUE TITLE
Xamarin.Facebook.Android fails to correctly generate android:authorities for <provider android:name="com.facebook.internal.FacebookInitProvider"> tag in generated AndroidManifest.xml

### ISSUE THREAD

**Issue by rrispoli** [xamarin/FacebookComponents#37]
The last version 4.22 doesn't generate the FacebookInitProvider correctly.

There are 3 related bugs about this:

https://bugzilla.xamarin.com/show_bug.cgi?id=51689
https://bugzilla.xamarin.com/show_bug.cgi?id=56690
https://bugzilla.xamarin.com/show_bug.cgi?id=56915

**Comment by Kritarie** [comment]
Looks like this issue is resolved in the latest v4.24.0. Perhaps an issue in the v4.22.0 .aar?

**Comment by rrispoli** [comment]
Yes, the v4.24.0 solve the problem. This issue can be closed.
