### ISSUE TITLE
iOS 7 and 8 not supported?

### ISSUE THREAD

**Issue by rihadavid** [xamarin/FacebookComponents#48]
Every time I try to log in on iOS 7 and 8, the app crashes, right after clicking the Facebook button.
So iOS 7 and 8 is now not supported? Why, could this be fixed?
I am using version 4.27.1.

**Comment by SotoiGhost** [comment]
@rihadavid I can reproduce the error with iOS 8.X or below and seems that this error has happened before as we can see here: https://developers.facebook.com/bugs/187865784990504/

I haven't found the solution yet and the bug report says that after a reboot the app started working again, so, can you try that? Meanwhile, I will continue investigating this.

**Comment by SotoiGhost** [comment]
@rihadavid Can you [file a bug][1] on Facebook explaining what's happening, please? According to this [answer][2], this is a bug on their end.

I'm closing this issue now. If something else happens related to this, feel free to re-open the issue again.

Best.

[1]: https://developers.facebook.com/bugs/
[2]: https://developers.facebook.com/bugs/1228940793834467/?comment_id=1725676701029485
