### ISSUE TITLE
Facebook login not working in Kitkat device

### ISSUE THREAD

**Issue by georgethms10** [xamarin/FacebookComponents#50]
Facebook xamarin android version:- **4.26.0**
**Issue:** Cannot login via Facebook when the facebook app is installed in the phone.
**Actual behaviour:**- Facebook button does not respond
**Expected behaviour:**- app should properly launch and return result from Facebook

In Kitkat device i noticed that if the **Activity LaunchMode is SingleInstance** it wont show the facebook page, If i **change** it back to **SingleTop or SingleTask** it works as expected.
How does the launch mode of the activity dependent on the facebook login?

**Comment by newky2k** [comment]
@georgethms10 Is this till an issue?

**Comment by newky2k** [comment]
no response for two weeks. closing
