### ISSUE TITLE
fb120136675352604 is not registered as a URL scheme. Please add it in your Info.plist

### ISSUE THREAD

**Issue by Inrego** [xamarin/FacebookComponents#51]
I get this exception when trying to call 

    var result = await loginManager.LogInWithReadPermissionsAsync(Constants.Constants.FacebookPermissions, vc);

I am using version 4.27.1, and according to the Getting Started article here: 
https://components.xamarin.com/gettingstarted/facebookios

It should only be necessary to add the following:

    <key>LSApplicationQueriesSchemes</key>
    <array>
            <string>fbapi</string>
            <string>fb-messenger-api</string>
            <string>fbauth2</string>
            <string>fbshareextension</string>
    </array>

**Comment by SotoiGhost** [comment]
@Inrego your Facebook App Id is missing inside of your Info.plist. There is a little section in docs that specify this:

> Info.plist
> In your Info.plist file of your project, go to the Advanced tab and add a URL Type. On the URL Schemes input write fbYour-Id-Here, replacing Your-Id-Here with your app Id.

**Comment by dilipchandima** [comment]
same issue here :(

**Comment by manhquyen** [comment]
same hear issue with react native 0.59.9 and fbsdk 0.8.0 :((
