### ISSUE TITLE
Anyway to have the latest update? 

### ISSUE THREAD

**Issue by ahmad-crossplatform** [xamarin/FacebookComponents#53]
Hello is it possible to run this again and  have the latest SDK  from facebook ? if yes how can we do that ?

**Comment by S1r-Lanzelot** [comment]
You must download the repo and update the build files to point to the latest version and then run it. There will more likely than not be build errors that youll have to deal with.
OR
Go to [maven](https://mvnrepository.com/artifact/com.facebook.android) and download the latest aar files and add them to their proper directories then rebuild the solution. You may need to do some tweaks to the bindings for any errors that occur.

**Comment by newky2k** [comment]
@ahmad-crossplatform  Facebook has been updated a couple times now, since the posting.
