### ISSUE TITLE
Crash Occurs Signing into Facebook while on iOS8.

### ISSUE THREAD

**Issue by BFGJbett** [xamarin/FacebookComponents#55]
The crash "Xamarin.iOS: Received unhandled ObjectiveC exception: NSInvalidArgumentException *** setObjectForKey: object cannot be nil (key: logging_token)" is received when attempting to sign into Facebook on a device running iOS8. This crash will not occur if the same project setup is used on a just an Xcode project. The quickest way to repo the issue is to use the Facebook sample while using the latest Xamarin.Facebook.iOS package in the nuget store. Simply hitting the Continue with Facebook causes the issue.

**Comment by SotoiGhost** [comment]
It seems that this error has happened before as we can see here: https://developers.facebook.com/bugs/187865784990504/ but according to this [answer][2], this is a bug on their end.

Can you [file a bug][1] on Facebook explaining what's happening, please?

I'm closing this issue now. If something else happens related to this, feel free to re-open the issue again.

Best.

[1]: https://developers.facebook.com/bugs/
[2]: https://developers.facebook.com/bugs/1228940793834467/?comment_id=1725676701029485
