### ISSUE TITLE
Sharing link failed using ShareLinkContent.Builder

### ISSUE THREAD

**Issue by johnfurog** [xamarin/FacebookComponents#64]
Sharing link using ShareLinkContent.Builder was working fine then, until few weeks ago.

 Everything is still working just like the same , except the link I am sharing is getting this  "Message could not be sent.Tap for details"  at the messenger.

![image](https://user-images.githubusercontent.com/33830386/39109766-df1d2bf6-4700-11e8-9aab-bc988ff0ad45.png)

**Comment by S1r-Lanzelot** [comment]
What do the "tap for details" say?

**Comment by johnfurog** [comment]
it says "you cant reply to this conversation"

**Comment by sharadunni** [comment]
is there a fix for this? our shares from app is broken to FB Messenger.

**Comment by S1r-Lanzelot** [comment]
Can you add debug information?

**Comment by Redth** [comment]
Closed because no new info.  Please open a new issue if there are problems with the lastest SDK bindings.
