### ISSUE TITLE
Couldn't get callback from Implementation of the Facebook.ShareKit.ISharingDelegate  on Xamarin.Facebook.Ios

### ISSUE THREAD

**Issue by PauloJoseBR** [xamarin/FacebookComponents#65]
Hi people,
I implemented Facebook.ShareKit.ISharingDelegate interface in order to get Callback from the user sharing, In other words, if the user opens the Sharing Webview the app should know the result(DidComplete, DidFail or DidCancel). That's something like IFacebookCallback interface from Xamarin.Facebook.Android. Below, it's my code. MyShareDelegate doesn't execute any of its methods. 

Thanks. 

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Foundation;
using MRV.AppCliente.Shared.Util.Constants;
using UIKit;
using Xamarin.Auth;
using Xamarin.Forms;
using Xamarin.Forms.Platform.iOS;
using Facebook.ShareKit;
using Facebook.CoreKit;
using Facebook.MessengerShareKit;
using Facebook.LoginKit;
using MRV.AppCliente.Mobile.Forms.Views;

[assembly: ExportRenderer(typeof(IndicacaoPremiadaDoisPage), typeof(MRV.AppCliente.Mobile.iOS.CustomRenderers.CompartilharNoFacebookRenderer))]

namespace MRV.AppCliente.Mobile.iOS.CustomRenderers
{
    public class CompartilharNoFacebookRenderer : PageRenderer
    {
        public override void ViewDidAppear(bool animated)
        {
            base.ViewDidAppear(animated);
            IEnumerable<Account> contas = null;
            contas = AccountStore.Create().FindAccountsForService("Facebook");

            var x = "https://g1.globo.com/rj/rio-de-janeiro/noticia/jungmann-diz-que-principal-linha-de-investigacao-da-morte-de-marielle-e-envolvimento-de-milicias.ghtml";

            MessagingCenter.Subscribe<Object>(this, AppConstants.MetodosMessagingCenter.CHAMAR_COMPARTILHAR_NO_FACEBOOK_IOS, (s) =>
            {

                foreach (var conta in contas)
                {
                    AccountStore.Create().Delete(conta, "Facebook");
                }

                var content = new ShareLinkContent();
                content.SetContentUrl(NSUrl.FromString(x));


                ShareDialog shareDialog = new ShareDialog();
                shareDialog.SetDelegate(new MyShareDelegate());
                shareDialog.SetShareContent(content);
                shareDialog.FromViewController = UIApplication.SharedApplication.KeyWindow.RootViewController;

                shareDialog.Mode = ShareDialogMode.FeedWeb;
                 
                
                shareDialog.Show();
            });


        }

        public override void ViewDidDisappear(bool animated)
        {
            MessagingCenter.Unsubscribe<Object>(this, AppConstants.MetodosMessagingCenter.CHAMAR_COMPARTILHAR_NO_FACEBOOK_IOS);
        }

    }

    public class MyShareDelegate : Facebook.ShareKit.ISharingDelegate
    {
        public IntPtr Handle { get; }

        public void DidComplete(Facebook.ShareKit.ISharing sharer, NSDictionary results)
        {

        }

        public void DidFail(Facebook.ShareKit.ISharing sharer, NSError error)
        {

        }

        public void DidCancel(Facebook.ShareKit.ISharing sharer)
        {

        }

        public void Dispose()
        {

        }
    }
}
```

**Comment by lyncstreamdevlf** [comment]
I am having the same problem with the Xamarin.Facebook.IOS.  Sharing a link to Facebook works, but the ISharingDelegate callback methods never get called.  I would expect after a successful post, that the DidComplete method would get called, but none of the events ever fire.

`var content = new ShareLinkContent();
ShareDialog shareDialog = new ShareDialog();
MyShareDelegate myShareDelegate = new MyShareDelegate();
shareDialog.SetDelegate(myShareDelegate);

content.SetContentUrl(NSUrl.FromString("http://www.google.com"));

shareDialog.SetShareContent(content);
shareDialog.FromViewController = this;
shareDialog.Mode = ShareDialogMode.Automatic;
shareDialog.Show();

public class MyShareDelegate : ISharingDelegate
{
	public IntPtr Handle { get; }

	public void DidComplete(ISharing sharer, NSDictionary results)
	{
		
	}

	public void DidFail(ISharing sharer, NSError error)
	{
		
	}

	public void DidCancel(ISharing sharer)
	{
		
	}

	public void Dispose()
	{
		
	}
}`

**Comment by SotoiGhost** [comment]
@PauloJoseBR, @lyncstreamdevlf Please, make sure that `MyShareDelegate` inherits from `NSObject` and delete the `Handle` property and the `Dispose` method, `NSObject` will handle that. Here's how the class must look like:

```csharp
public class MyShareDelegate : NSObject, ISharingDelegate {
	public void DidComplete (ISharing sharer, NSDictionary results)
	{

	}

	public void DidFail (ISharing sharer, NSError error)
	{

	}

	public void DidCancel (ISharing sharer)
	{

	}
}
```

Also, you must retain an instance of the `MyShareDelegate` class in your `ViewController` class so the delegate can be called:

```csharp
namespace YourNamespace.iOS {
	public class YourPageRenderer : PageRenderer, ISharingDelegate {
		MyShareDelegate myShareDelegate;

                ...

		void ShareSomething ()
		{
			...

			myShareDelegate = new MyShareDelegate ();

			var shareDialog = new ShareDialog ();
			shareDialog.SetDelegate (myShareDelegate);

			...

			shareDialog.Show ();
		}
}
```

If something else happens related to this, please, feel free to reopen this issue.

Best,
Israel Soto.

**Comment by PauloJoseBR** [comment]
I opened a ticket to Microsoft and they told me that is a Facebook bug.

**Comment by AshishtChetu** [comment]
Hi, 

I am still facing this issue, ISharingDelegatee not calling any of the callback. Is there any updates on this from facebook.

Thank you.
