### ISSUE TITLE
iOS component causes binary rejection due to Bluetooth usage

### ISSUE THREAD

**Issue by ugurpelister** [xamarin/FacebookComponents#72]
I upgraded my iOS project's Facebook component from Nuget (v4.33.0), and sent a new build to iTunes for review. The binary was immediately rejected.

The email from iTunes stated that:

> Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSBluetoothPeripheralUsageDescription key with a string value explaining to the user how the app uses this data.

I was totally puzzled because there is no single line of code related to Bluetooth usage in my code. After some trial and error, I downgraded Facebook component version and the new build got accepted.

I don't think that Facebook's official libraries use any Bluetooth functions. Is this a Xamarin-specific issue? Why are we supposed to add `NSBluetoothPeripheralUsageDescription` key just for Facebook-related activities?

**Comment by S1r-Lanzelot** [comment]
The update of v4.32 contained Places Kit which contains bluetooth scanning. https://github.com/xamarin/FacebookComponents/pull/66
