### ISSUE TITLE
Xamarin.Facebook.Android v.4.26.0: How to use AppLinkData.FetchDeferredAppLinkData()?

### ISSUE THREAD

**Issue by bunnywrote** [xamarin/FacebookComponents#74]
Can you give an example how to use the method AppLinkData.FetchDeferredAppLinkData(...) in Xamarin.Facebook.Android v.4.26.0?

**Comment by Redth** [comment]
Unfortunately we can't provide documentation or samples of all the third party API's we provide bindings for.  This blog article looks like it should be helpful: https://www.oodlestechnologies.com/blogs/Facebook-App-Invites-in-Android

The java code for any example of using these API's should be pretty similar and easy to translate to C#.  Good luck!
