### ISSUE TITLE
[iOS][AudienceNetwork.iOS] Sometimes InterstitialAdWillClose () is not called.

### ISSUE THREAD

**Issue by KazumaShimomiya** [xamarin/FacebookComponents#75]
Hello.

I'd like to display interstitialAd using Audience Network.
However, I found a little problem with iOS.
With IInterstitialAdDelegate, the Delegate method (InterstitialAdWillClose () or InterstitialAdDidClose ()) should be called when the ad is closed, but sometimes the Delegate method is not called.
We prepared all methods that we can export, but even IntersitialDidFail () is not called.

Is this a bug?
There was no particular problem when using AdMob's mediation.
I want hints to solve if it is not a bug.

I am sorry if this is a Google translation, so it makes sense for me.

Thank you.

**Comment by newky2k** [comment]
@KazumaShimomiya  could you please provide a samle demo project that replicate this issue that you are having.

**Comment by newky2k** [comment]
no response for two weeks. closing
