### ISSUE TITLE
Facebook.AccountKit.iOS crash on release only

### ISSUE THREAD

**Issue by lDemurl** [xamarin/FacebookComponents#76]
Hi, when I use this:

`PhoneLogin.AsIViewControllerProtocol()`

The registrar found an invalid interface 'Facebook.AccountKit.IViewController': The interface must have a Protocol attribute specifying its wrapper type

In debug works fine

**Comment by lDemurl** [comment]
I resolved with --linkskip

**Comment by SotoiGhost** [comment]
Hi @lDemurl! Thanks for reporting this! I'll investigate this, it seems that something is being stripped by the linker.
