### ISSUE TITLE
[iOS] Component version 4.33.0 is rejected by the App Store

### ISSUE THREAD

**Issue by dtaylorus** [xamarin/FacebookComponents#77]
The only change in my app submission was to update the Xamarin.iOS Facebook nuget package from version 4.27.1 to 4.33.0.

The submission with 4.27.1 passed and the version with 4.33.0 was rejected with the following error:

> **Missing Info.plist key -** This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSBluetoothPeripheralUsageDescription key with a string value explaining to the user how the app uses this data.

I really don't want to ask for Bluetooth permissions when the only Facebook feature I'm using is login. There is no plausible explanation for why my game would need this permission. It doesn't even have advertising to use as an excuse.

**Comment by dtaylorus** [comment]
Update: I downgraded to component version 4.30.0, and that passed App Store submission, which narrows the problem down to a change between 4.30.0 and 4.33.0.

**Comment by S1r-Lanzelot** [comment]
https://github.com/xamarin/FacebookComponents/issues/72 for explanation of change.

I agree - It would be nice to have each Facebook SDK presented as individual nuget packages so that it is not an all or nothing scenario.

**Comment by SotoiGhost** [comment]
@dtaylorus @S1r-Lanzelot Now, Facebook has been split. Now you can avoid using the Framework part that you don't want to use. There will continue to be available the `Xamarin.Facebook.iOS` NuGet for backward compatibility. It will be just an empty shell that references others Facebook NuGets.

I'm closing this now, feel free to reopen it if something else happens.

Best,
Israel Soto.

**Comment by dtaylorus** [comment]
That’s perfect. Thank you!

________________________________
