### ISSUE TITLE
Facebook account kit error - xamarin android visual studio 2017

### ISSUE THREAD

**Issue by balajikarthiq** [xamarin/FacebookComponents#78]
I installed the facebook account kit via nuget and getting below error while building the application.
version: 4.28.0

> error: OnSpinnerEventsListener is not public in CountryCodeSpinner;
> cannot be accessed from outside package
> com.facebook.accountkit.ui.CountryCodeSpinner.OnSpinnerEventsListener
> App8
> ..\obj\Debug\android\src\mono\com\facebook\accountkit\ui\CountryCodeSpinner_OnSpinnerEventsListenerImplementor.java
> 8

it says the `OnSpinnerEventsListener` is not public in CountryCodeSpinner. But how can i modify it? Or is there anything need to be added in the xamarin application to build it successfully.

**Comment by S1r-Lanzelot** [comment]
I believe there is something wrong with the bindings - The spinner needed to be excluded. It is not usable right now as far as I know.

**Comment by balajikarthiq** [comment]
Is there any workaround for this issue. because i can't modify the java files.

**Comment by S1r-Lanzelot** [comment]
I am not aware of any way to change the bindings in the consuming application.

If you want, you can pull down the bindings I made for AccountKit, build the project, and then use the dlls from that. They work for sure (I use them in my own applications since this repo is currently broken).

https://github.com/S1r-Lanzelot/FacebookComponents/tree/AccountKitAndroid

**Comment by S1r-Lanzelot** [comment]
The ios AccountKit bindings from Nuget should work fine so you'll only have to worry about supplying the Android bindings.

**Comment by balajikarthiq** [comment]
let me check on that. i'm building the android app.

**Comment by S1r-Lanzelot** [comment]
Ya let me know if you have any questions on building it, etc. - hopefully this repo can get fixed soon.

**Comment by balajikarthiq** [comment]
your project also throws an compilation error. Is there anything needs to be download and install for windows system. You've mentioned some settings for OS X, Is it required for windows system?

**Comment by balajikarthiq** [comment]
https://www.nuget.org/packages/Naxam.AccountKit.Droid/  it's not working.. same spinner error and two more errors also.

**Comment by S1r-Lanzelot** [comment]
OK well in my repo you should run ` ..\build.ps1 -t libs` within the `Facebook.Android` directory to build the bindings. That should work

**Comment by balajikarthiq** [comment]
Thanks, working fine

**Comment by tuyen-vuduc** [comment]
@balajikarthiq I haven't never got error with `Naxam.AcountKit.Droid`. If you faced any error, it would be better to log issue, so we could know and find a solution for it.

**Comment by Redth** [comment]
This should be solved in newer versions.  Please open a new issue if there are problems with the latest version.

**Comment by nguyenvantan25011996** [comment]
Thanks, working fine
Hi, can you show me detail to fix this problem. thanks you!

**Comment by nguyenvantan25011996** [comment]
> OK well in my repo you should run ` ..\build.ps1 -t libs` in powershell within the `Facebook.Android` directory to build the bindings. That should work
Hi, Can you show me detail to fix this problem? Thanks you!
