### ISSUE TITLE
[Android] Adding Xamarin.Facebook.Android package causes build warnings

### ISSUE THREAD

**Issue by SarahAnnTolsma** [xamarin/FacebookComponents#80]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3,3): Warning: Duplicate managed type found! Mappings between managed types and Java types must be unique. First Type: 'Xamarin.Facebook.GraphRequestAsyncTask, Xamarin.Facebook.Common.Android, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'; Second Type: 'Xamarin.Facebook.GraphRequestAsyncTask, Xamarin.Facebook.Login.Android, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. (test)

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3,3): Warning: References to the type 'Xamarin.Facebook.GraphRequestAsyncTask' will refer to 'Xamarin.Facebook.GraphRequestAsyncTask, Xamarin.Facebook.Common.Android, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. (test)

**Comment by SarahAnnTolsma** [comment]
Version 4.33.0

**Comment by smallcandles** [comment]
+1

**Comment by newky2k** [comment]
@SarahAnnTolsma can you try the latest version -> https://www.nuget.org/packages/Xamarin.Facebook.Android/  4.34.0. it was released two weeks ago.  thanks

**Comment by Georgeaux** [comment]
I tried v4.34.0, same story 

warning : Duplicate managed type found! 
Mappings between managed types and Java types must be unique. 
First Type: 'Xamarin.Facebook.GraphRequestAsyncTask, Xamarin.Facebook.Common.Android, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'; 
Second Type: 'Xamarin.Facebook.GraphRequestAsyncTask, Xamarin.Facebook.Login.Android, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by newky2k** [comment]
@Georgeaux  i have assigned an engineer to look into it

**Comment by thisisthekap** [comment]
@newky2k When is this fix going to be released?

**Comment by zonkzen** [comment]
This should not be closed!!
@newky2k when will you fix it??

**Comment by thisisthekap** [comment]
@zonkzen To my understanding the fix was already implemented.

@newky2k Is there already an ETA when this fix will make it into a stable release?

**Comment by Redth** [comment]
This should be fixed in 4.37 when it's released (which should be any moment now)
