### ISSUE TITLE
version conflict with xamarin.Android.Support.Design

### ISSUE THREAD

**Issue by Jcardif** [xamarin/FacebookComponents#82]
version 4.33.0 of Xamarin.Facebook.Android coflicts with version 27.0.2.1 of  xamarin.Android.Support.Design. Kindly update

> Severity	Code	Description	Project	File	Line	Suppression State
> Error		Version conflict detected for Xamarin.Android.Support.Compat. Reference the package directly from the project to resolve this issue. 
>  e-SpaMobileApp -> Xamarin.Android.Support.Design 27.0.2.1 -> Xamarin.Android.Support.Compat (= 27.0.2.1) 
>  e-SpaMobileApp -> Xamarin.Facebook.Android 4.33.0 -> Xamarin.Facebook.Common.Android 4.33.0 -> Xamarin.Android.Support.CustomTabs 27.0.2 -> Xamarin.Android.Support.Compat (= 27.0.2).			0

**Comment by newky2k** [comment]
No response for two weeks. closing
