### ISSUE TITLE
May I know the Android 4.34 supports codeless app event?

### ISSUE THREAD

**Issue by siuhleung7** [xamarin/FacebookComponents#86]
I now using the 4.34 for Android, but seems doesn't working.

I added this to AndroidManifest.xml, but couldn't found fb_codeless_debug in event debug.
`<meta-data android:name="com.facebook.sdk.CodelessDebugLogEnabled" android:value="true" />`

> Can't Connect?
> Check this list then close and reopen your app and try again.
> Your app has Facebook SDK v.4.34 or higher.
> You're using the latest version of your app.
> You're shaking your phone firmly enough.
> If your WiFi is unreliable, connect to high-speed Internet.

The iOS 4.35 is working perfectly for fb_codeless_debug.

Thank you very much.

**Comment by siuhleung7** [comment]
Oh, I found the Android Integration said **Note**: Only works for Facebook SDK v4.35 and above.
https://developers.facebook.com/docs/app-events/codeless-app-events

Could you please update to v4.35 or above and make it supports codeless app event

**Comment by newky2k** [comment]
@siuhleung7  an update 4.36 is being worked on currently and should be out in the near future.
