### ISSUE TITLE
Facebook login causes you to be taken to “Help Center” if we try to login multiple times

### ISSUE THREAD

**Issue by SRJgit18** [xamarin/FacebookComponents#88]
My app has multiple login options; of which FB Login is one of the options. Clicking "cancel" on the "confirm login" page on facebook login causes you to be taken to a troubleshooting page the next time you attempt.

Steps: Open the app that is not currently logged in but has been logged in using facebook in the past.

1 - Click on Login (Existing User)

2 - Click Login with Facebook

3 - You should be taken to a "confirm login" page where is tells you "you previously logged in to App with Facebook"

4 - Click cancel and it takes you to the Login screen

5 - Press "Login with Facebook" again

6 - If done consecutively you will be taken to the Facebook Help Center

Please let me know if this is an expected behaviour or this needs to be handled.

The error I am getting when clicking cancel is:
error_reason=user_denied
&error=access_denied
&error_description=Permissions+error.

More info:
We are using Xamarin.Facebook.iOS.4.27.1 nuget package.

We are logging in to account as per "LoginButtonCompletedEventArgs.Result".
If "LoginButtonCompletedEventArgs.Result.Token" is not null, that is taken forward for successful login and hence proceeded.

In the reported bug scenario, we are getting
"LoginButtonCompletedEventArgs.Result.IsCancelled" as TRUE when we click "Cancel" in login confirmation page as well as "Done" in Help Center page.

Could you kindly try replicating the issue using the above mentioned package?
Also please let me know if this issue, "authorize/?error=access_denied&error_code=200&error_description=Permissions+error&error_reason=user_denied" when triggered multiple times could make Facebook suggest the user to report the app for any suspected attack?

<img width="592" alt="help center" src="https://user-images.githubusercontent.com/43267756/45543709-dbc81a80-b832-11e8-88e0-67a5bb92b819.png">

**Comment by newky2k** [comment]
@SRJgit18 4.35.0 was release two weeks ago and there are serveral newer versions of Xamarin.Facebook.iOS before that, that are new than the version you are using.  Could you please try the latest version.

Regards

**Comment by SRJgit18** [comment]
Thanks for the reply @newky2k . I tried with Xamarin.Facebook.iOS version 4.35.0, and still able to reproduce the issue. Quoting from my original post, 

> please let me know if this issue, "authorize/?error=access_denied&error_code=200&error_description=Permissions+error&error_reason=user_denied" when triggered multiple times could make Facebook suggest the user to report the app for any suspected attack?

**Comment by SotoiGhost** [comment]
@SRJgit18 I tried reproducing this using v4.38.0 with no success, can you try with the most recent version of Facebook and see what happens? Thanks in advance!

**Comment by SotoiGhost** [comment]
We are closing this issue since no response was received. Please open a new issue referring to this one if you have more information.

**Comment by Scy15** [comment]
I am also facing the same issue. Have tried all the changes you mentioned, including updating to v4.38.0. Could you please look into this and reopen this issue?
