### ISSUE TITLE
Facebook Api 3.1 support

### ISSUE THREAD

**Issue by softsan** [xamarin/FacebookComponents#89]
We got an email from facebook for API upgrade. It ask to upgrade to Facebook API v3.1 from current 2.7.

<img width="1143" alt="screen shot 2018-09-21 at 9 32 50 pm" src="https://user-images.githubusercontent.com/7391319/45892544-0e9b8100-bde6-11e8-86de-0dc05f79f3e6.png">

Currently we used Xamarin.facebook.android 4.34 and Xamarin.facebook.iOS 4.35
So when can we expect that upgraded FB API 3.1 in nugget package for Xamarin.android and Xamarinn.iOS?

Thanks.

**Comment by caseyniemann** [comment]
Agreed. When can we expect an update

**Comment by obader** [comment]
any update on the issue as Facebook will block our app access

**Comment by SotoiGhost** [comment]
Hi guys! Currently, `Xamarin.Facebook.iOS` v4.35.0 has support up to graph API v3.1 and `Xamarin.Facebook.Android` v4.34.0 has support up to v3.0.

The Facebook's email is just a reminder for you that it's time to update the very old SDK (in case you use it) before they cannot longer support you. For example, if you are implementing FB iOS v4.21.0 (that supports up to API 2.8) it's time to upgrade to v4.22.0 or later.

The SDKs uses the most recent graph API version by default at the point they were released. You can override the default version using the [`GraphApiVersion`][ios] property on iOS and the `SetGraphApiVersion` method on Android.

Here are the original docs of this: [iOS][ios-doc] and [Android][android-doc].

`Xamarin.Facebook.Android` v4.36.0 has already a PR and it's in a review process and `Xamarin.Facebook.iOS` will be released in the following weeks.

If you have any doubt, don't hesitate to ask.

Hope this helps.

Best,
Israel Soto.

[ios]: https://github.com/xamarin/FacebookComponents/blob/master/Facebook.iOS/CoreKit/source/Facebook.CoreKit/ApiDefinition.cs#L983
[ios-doc]: https://developers.facebook.com/docs/reference/iossdk/4.36.0/FBSDKCoreKit/classes/fbsdksettings.html#graphAPIVersion
[android-doc]: https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/facebooksdk.html/#setgraphapiversion-javalangstring-

**Comment by softsan** [comment]
hi,

we received this email from facebook:

_YourProject currently uses Facebook SDK for **Android v4.34.0 and Facebook SDK for iOS v4.35.0**, both of which rely on the recently deprecated Version 2.7 of the Graph API.
As a result, there is a risk that your app will no longer function if you don't upgrade to Facebook SDK for **Android v4.37.0 and Facebook SDK for iOS v4.37.0**.
As an admin of this app, please upgrade to the latest SDK as soon as possible to ensure your app's continued performance and to take advantage of new features._ 

So when can we expect the latest of facebook SDK for xamarin.android and Xamarin.iOS in nuget?
Thanks.

**Comment by softsan** [comment]
Can you please update nuget package or atleast when can we have the latest package?
