### ISSUE TITLE
Facebook iOS Unable to get permission to write

### ISSUE THREAD

**Issue by AJereli** [xamarin/FacebookComponents#90]
My app (Xamarin Forms) needs to use write permission for GraphRequest and wall-posting.

What I try to do:
Using Xamarin.Facebook.iOS (v 4.35)

        readonly LoginManager _loginManager = new LoginManager();
        readonly string[] _permissions = { @"public_profile", @"email", @"user_posts", @"user_photos"};
        LoginResult _loginResult;
        TaskCompletionSource<LoginResult> _completionSource;
        public Task<LoginResult> LoginWithPublish()
        {
            _completionSource = new TaskCompletionSource<LoginResult>();
            _loginManager.LogInWithPublishPermissions(_permissions, GetCurrentViewController(), LoginManagerLoginHandler);
            return _completionSource.Task;
        }

       void LoginManagerLoginHandler(LoginManagerLoginResult result, NSError error)
        {
            if (result.IsCancelled)
                _completionSource.TrySetResult(new LoginResult { LoginState = LoginState.Canceled });
            else if (error != null)
                _completionSource.TrySetResult(new LoginResult { LoginState = LoginState.Failed, ErrorString = error.LocalizedDescription });
            else
            {
                _loginResult = new LoginResult
                {
                    Token = result.Token.TokenString,
                    UserId = result.Token.UserId,
                    ExpireAt = result.Token.ExpirationDate.ToDateTime()
                };

                var request = new GraphRequest(@"me", new NSDictionary(@"fields", @"email"));
                request.Start(GetEmailRequestHandler);
            }
        }

So, when i try to call **LoginWithPublish**, handler **LoginManagerLoginHandler** is never called.
Just nothing is happing.

If I calling LoginWithReadPermissions (and same Handler), i can get login, but when i try call GraphRequest "{user_id}/photos?url="url"" a got this error (and it is quite logical).

```
Error Domain=com.facebook.sdk.core Code=8 "(null)" UserInfo={com.facebook.sdk:FBSDKGraphRequestErrorCategoryKey=0, com.facebook.sdk:FBSDKGraphRequestErrorHTTPStatusCodeKey=403, com.facebook.sdk:FBSDKErrorDeveloperMessageKey=(#200) Requires extended permission: publish_actions, com.facebook.sdk:FBSDKGraphRequestErrorGraphErrorCode=200, com.facebook.sdk:FBSDKGraphRequestErrorParsedJSONResponseKey={
    body =     {
        error =         {
            code = 200;
            "fbtrace_id" = DBHvrFFmvfB;
            message = "(#200) Requires extended permission: publish_actions";
            type = OAuthException;
        };
    };
    code = 403;
}}
```
But I unable just to add publish_actions to list of my permissions, that's related to update of FB api.

How I can get write permissions or any another way to do wall-post on FB with Xamarin.Forms?

**Comment by SotoiGhost** [comment]
We are closing this issue since no response was received. Please open a new issue referring to this one if you have more information.
