### ISSUE TITLE
Need to upgrade to version 4.37.0 based on Facebook Developers email received

### ISSUE THREAD

**Issue by xplatsolutions** [xamarin/FacebookComponents#91]
> SDK Upgrade: iOS v4.37.0  
> 
> {AppName} currently uses Facebook SDK for iOS v4.27.1, which relies on the recently deprecated Version 2.7 of the Graph API.
> 
> As a result, there is a risk that your app will no longer function if you don't upgrade to Facebook SDK for iOS v4.37.0.As an admin of this app, please upgrade to the latest SDK as soon as possible to ensure your app's continued performance and to take advantage of new features.

 Any plans upgrading?

**Comment by vdhyaram** [comment]
Please let us know if you have an ETA for the upgrade on the package.   we received the emails too and we have multiple apps at the risk of not working.

**Comment by newky2k** [comment]
@xplatsolutions @vdhyaram please look at the repsponse to this issue -> https://github.com/xamarin/FacebookComponents/issues/89.  We are looking on updating the components to support the latest version of FB on  iOS and Android.

Regards
