### ISSUE TITLE
AppEvent FacebookUninstallTracker

### ISSUE THREAD

**Issue by Jagbri** [xamarin/FacebookComponents#95]
I would like to track app uninstalls. Could you support the AppEvent FacebookUninstallTracker?

Thanks

**Comment by newky2k** [comment]
@Jagbri  Thanks for getting on contact.  @SotoiGhost  should be able to help you.

Regards

**Comment by SotoiGhost** [comment]
@Jagbri The current Facebook NuGet for Android has support for `FacebookUninstallTracker`. Please, follow [FB guide][1] to learn more abut this. Here's an example of how you can use it on your Activity:

```csharp
Xamarin.Facebook.AppEvents.FacebookUninstallTracker.UpdateDeviceToken (Firebase.Iid.FirebaseInstanceId.Instance.Token);
```

You will need to install `Xamarin.Facebook.Android`, `Xamarin.Facebook.Marketing.Android` and `Xamarin.Firebase.Messaging` NuGet packages.

Best!
Israel Soto.

[1]: https://developers.facebook.com/docs/app-events/uninstalls/
