### ISSUE TITLE
[iOS] v4.35 forcing me to drop support for iOS 7

### ISSUE THREAD

**Issue by rihadavid** [xamarin/FacebookComponents#97]
When I update to v4.35, I get a build error `The binding library 'Facebook.LoginKit.dll' contains a user framework (Facebook.LoginKit.dll), but embedded user frameworks require iOS 8.0 (the deployment target is FBSDKLoginKit.framework). Please set the deployment target in the Info.plist file to at least 8.0.`

So, that means that I can't use v4.35 and newer in my iOS project if I want to keep the deployment target on iOS 7? Why? Until now, I was using a runtime condition to check whether the iOS is 9.0+ and disable Facebook SDK otherwise. But this is now not possible.

Can this be fixed or is it now "iOS7 or v4.35"?

**Comment by newky2k** [comment]
@rihadavid  let me get @SotoiGhost  to look into this for you

Regards

**Comment by Redth** [comment]
This is a requirement of 4.35.0 on Facebook's part, not ours:
https://github.com/CocoaPods/Specs/blob/9543734012238c33ea018af5a4381459c13f0916/Specs/b/5/0/Facebook-iOS-SDK/4.35.0/Facebook-iOS-SDK.podspec.json#L13

So looks like you need to target 8.0 or higher to use this version as per the Podspec.  Sorry, but this one's out of our control.
